apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy-helm
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: ravpawarakslearn.azurecr.io/aks-learn:v2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret
