# k8s configmap
# not working
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-ingress
  namespace: default
annotations:
data:
  http-snippet: |
    limit_req_zone test zone=limit_rps:5m rate=5r/m;
  location-snippet: |
      limit_req zone=limit_rps;  
  