apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress2
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/limit-rpm: "5" # not working
spec:
  rules:
  - host: "rate-limit"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ps-clusterip
            port:
              number: 80
  ingressClassName: nginx

  # add rate limiting
  # https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#rate-limiting
