apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: ravpawarakslearn.azurecr.io/aks-learn:v1.0
      ports:
        - containerPort: 8080
